:verbose: false
:concurrency: 7

:timeout: 8
:queues:
  - [default, 4]
  - [mailers, 2]
  - [scoring, 1]
:schedule:
  scoring_check:
    cron: '0 * * * * *'
    class: ScoringCheck
    queue: scoring
  guest_clear:
    cron: '30 0 1 * *'
    class: GuestClear
  set_matchday:
    cron: '10 0 * * *'
    class: SetMatchday
  matchday_times:
    cron: '15 0 * * *'
    class: MatchdayTimes
  lock_queuer:
    cron: '0 0 * * *'
    class: LockQueuer
  reminder_queuer:
    cron: '5 0 * * *'
    class: ReminderQueuer